### ISSUE TITLE
Create 0.1 release

### ISSUE THREAD

**Issue by HenryOlson** [HenryOlson/optiq-web#10]

**Comment by julianhyde** [comment]
My release process is: get the build and tests running, update history.MD, mvn release:prepare, mvn release:perform. You will need maven-release-plugin.

**Comment by HenryOlson** [comment]
OK.  I think I've now gotten the right things in the pom.xml file.

Would you mind taking a quick look at my pom.xml (derived from yours for optiq-csv)?

I did notice some stuff about the pentaho repository - not sure if this is correct / appropriate.

Thanks,

**Comment by julianhyde** [comment]
I've made a couple of comments on your github commits. When those are done, and when HISTORY.md is in good shape, we're good to go.

The maven release plugin updates pom.xml in two separate commits, pushes the binaries, updates the site (if you have one), adds a release tag, and then pushes the commits up to github.

If you like I could press the button to do the actual release, since I have credentials to push the binaries to conjars.org. You'd need to make me a collaborator on optiq-web so that I can commit to it.

Julian

**Comment by HenryOlson** [comment]
OK - I've addressed your comments re pom.xml and unit tests.  I've also updated HISTORY.md.

You have been added as a committer and I would welcome your help in doing the release.  Please share a bash history of the release if you would so I can learn the process.

The only open question in my mind is whether to release with the equijoin warnings.  May be tough to fix since optiq-web is currently built against optiq 0.4.18.

Thoughts?

**Comment by julianhyde** [comment]
On Feb 28, 2014, at 1:03 PM, Henry Olson notifications@github.com wrote:

> OK - I've addressed your comments re pom.xml and unit tests. I've also updated HISTORY.md. 
> 
> You have been added as a committer and I would welcome your help in doing the release. Please share a bash history of the release if you would so I can learn the process. 
> 
> The only open question in my mind is whether to release with the equijoin warnings. May be tough to fix since optiq-web is currently built against optiq 0.4.18. 
> 
> Thoughts? 

I'd have to make a release of optiq and the warnings are basically a cosmetic issue. I'll get to them in the next week or so but you shouldn't wait. You could add a note that they are nothing to worry about.

I'm ready to make the release. Just say the word.

Julian

**Comment by HenryOlson** [comment]
I've updated the README; release when ready.

**Comment by julianhyde** [comment]
OK, I've made the release. Congratulations on 0.1!

https://github.com/HenryOlson/optiq-web/releases

https://github.com/HenryOlson/optiq-web/commits/master

And deployed to conjars.org:

http://conjars.org/net.hydromatic/optiq-web

I also created a site, populated by maven:

http://www.hydromatic.net/optiq-web/

The steps I use to release are:

mvn -s ~/.m2/settings.xml release:clean release:prepare
mvn -s ~/.m2/settings.xml -DskipTests release:perform
mvn clean

settings.xml contains my credentials to push to conjars, so I don't check it in.

Julian

**Comment by HenryOlson** [comment]
Thanks, Julian.  I very much appreciate your walking me through the process.
