### ISSUE TITLE
Best approach for system test?

### ISSUE THREAD

**Issue by HenryOlson** [HenryOlson/optiq-web#11]
I'm in the habit of running ./sqlline -f target/test-classes/webjoin.sql as an end-to-end test.  Is there a good way to add this or something better to the Junit tests or as a separate mvn target?

**Comment by julianhyde** [comment]
you could invoke sqlline from within a junit test and catch and compare its stdout. (sqlline supports redirection of stdout, I think.)

or, better, create a jdbc connection, run a statement via jdbc, compare the results. CsvTest.checkSql does this. Feel free to copy.

**Comment by julianhyde** [comment]
By the way, you may see flakiness due to wikipedia being unavailable. (E.g. if you run the test while on a plane.) The most robust approach would be tests that you can run while offline. Use file: protocol or maybe a mock HTTP server.

**Comment by HenryOlson** [comment]
Working on that now.

**Comment by HenryOlson** [comment]
Good idea.  I'll take a look at CsvTest.checkSQL.
