### ISSUE TITLE
Saiku over Optiq-web

### ISSUE THREAD

**Issue by buggtb** [HenryOlson/optiq-web#29]
Hey Henry

I shared this on twitter but didn't know where best to share this with you, so I've created a non issue for you as I thought you might like to see Saiku over Wikipedia thanks to your connector :)

Tom

![untitled](https://f.cloud.github.com/assets/103544/2472427/6e310be4-b035-11e3-89a7-5a76a524b93e.png)

**Comment by HenryOlson** [comment]
Tom,
I'm astonished you were able to breathe life into this long-forgotten project.  I remember being tickled at being able directly query an HTML table - hope you were too.
Thanks for sharing this.
Best,
Henry

**Comment by HenryOlson** [comment]
And I'm seeing now that this was done 10 years ago ;^).

**Comment by buggtb** [comment]
Yeah it's an old one, but it was a cool project when I needed it, thanks for creating it!

**Comment by julianhyde** [comment]
Optiq-web lives on... it has been absorbed into Calcite as the [file adapter](https://calcite.apache.org/docs/file_adapter.html).

Now you just need to dust off Saiku, Tom... someone was telling me the other day that Mondrian is having a revival, and Calcite now has measures.

**Comment by buggtb** [comment]
I extracted the rights and code so one day when I find the time it might happen! :)
